### ISSUE TITLE
add funkemunky

### ISSUE THREAD

**Issue by icewormy3** [GreatZardasht/official-skid-list#2]
known for renaming latestncp to sentinel

**Comment by GreatZardasht** [comment]
> known for renaming latestncp to sentinel

Will do, any screenshots or juicy shit i can use?

**Comment by GreatZardasht** [comment]
ok, added, if you want i will keep this open for 2 more days and you can suggest some more shit for me to add about him

**Comment by icewormy3** [comment]
https://www.youtube.com/watch?v=PDuZIFvVe4Y talks about skidding ncp 1:12:30

**Comment by icewormy3** [comment]
bans people with fake sentinel messages https://www.youtube.com/watch?v=8udLTfmJBRc&t=70s

**Comment by GreatZardasht** [comment]
> bans people with fake sentinel messages https://www.youtube.com/watch?v=8udLTfmJBRc&t=70s

pog, should iclose the issue or do you want me to add more info?

**Comment by icewormy3** [comment]
i mean thats all I have so im gona close it
